### ISSUE TITLE
immediate crash when trying to edit style (color) of mouse speed indicator

### ISSUE THREAD

**Issue by surepy** [ThoNohT/NohBoard#48]
exactly what title says.

``` 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ThoNohT.NohBoard.Forms.Style.MouseSpeedStyleForm..ctor(MouseSpeedIndicatorStyle initialStyle, MouseSpeedIndicatorStyle defaultStyle)
   at ThoNohT.NohBoard.Forms.MainForm.mnuEditElementStyle_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2115.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NohBoard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/sleepy/Desktop/unwnbinary-temp!/nohboard/NohBoard.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
NohBoard.Hooking
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/sleepy/Desktop/unwnbinary-temp!/nohboard/NohBoard.Hooking.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2112.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2112.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2112.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
clipper_library
    Assembly Version: 6.2.1.0
    Win32 Version: 6.2.1.0
    CodeBase: file:///C:/Users/sleepy/Desktop/unwnbinary-temp!/nohboard/clipper_library.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by joao7yt** [comment]
I had the same few days ago, that only happened when trying to edit a mouse speed indicator from a specific keyboard definition. On mine, for example, that’s good.

Didn’t help deleting and addind a new one...

**Comment by ThoNohT** [comment]
Time for me to get back to NohBoard. I've spent the last few weeks working against some deadlines at work, but I hope to get more free time from now on. I'm going on holiday next week, after that I'll try to schedule some time to work on this.

Please attach a keyboard definition and style that cause this exception.

**Comment by joao7yt** [comment]
This keyboard is from that guy on the forum that i helped. This contains a custom font.

https://mega.nz/#!fZcCDBID!mM4BUDF9CqeFrGq9qnRbi1G1efy6lylvY3KapXA0BFM

**Comment by sleepychan** [comment]
i use this one

keyboard definition: https://gist.github.com/sleepychan/465c4770b789009d0ec9ff0d40359a46
style: (default)

**Comment by ThoNohT** [comment]
Fixed in 8181d77de22b8036b5de428d1e02293373357046
I'll release v1.0.1.

**Comment by joao7yt** [comment]
So, tested it and found out that when the Mouse Speed Indicator Style, the colors are set back to the default grey and white.

**Comment by ThoNohT** [comment]
Right. It's never this easy 😄 
Could you give this version a try? I even found a crash when opening the keyboard style form after enabling and disabling a style override for an element.

https://ci.appveyor.com/project/ThoNohT/nohboard/build/1.0.59/artifacts

**Comment by joao7yt** [comment]
just tested it and it still setting the Speed Indicator colors to grey and white after opening the Mouse Speed Indicator Style. About the crash you mentioned: nothing here

**Comment by ThoNohT** [comment]
I'm not seeing the problem you mention. If I set the element style, and re-open the dialog, it keeps the custom colors. Even when saving the style, and reloading NohBoard, it uses the colors I picked.

It does reset to the default if you disable the overwrite, and then reopen the style dialog, but that is normal behavior, and happens for all keys.

**Comment by joao7yt** [comment]
Ok, i will record a video, give me 5 min

**Comment by joao7yt** [comment]
Really weird behavior... checkboxes being checked without me cheking it, and even unchecking, not behaving right: https://youtu.be/vpX9hU3PR4k

**Comment by ThoNohT** [comment]
Yep, I see what you mean. I made two more small changes. This now should behave as it is supposed to:

https://ci.appveyor.com/project/ThoNohT/nohboard/build/1.0.61/artifacts

**Comment by joao7yt** [comment]
Tested right now and it seems working fine. I think this can be closed.
